import { Post } from '@/types/post';

export const posts: Post[] = [
    {
        id: '1',
        userName: 'Ada Lovelace',
        userHandle: 'ada_l',
        content: 'Probando mi primera app de Mini Twitter en React Native 🚀',
        userAvatar: require('../assets/avatar/av1.jpg'),
        likes: 12,
        retweets: 3,
        replies: 1,
    },
    {
        id: '2',
        userName: 'Linus Torvalds',
        userHandle: 'linus_t',
        content: 'Git fue un accidente… pero uno muy útil 😎',
        // userAvatar: require('../assets/avatar/av2.jpg'),
        imageUrl: 'https://cdn-carlos.sanchezdonate.com/wp-content/uploads/cover-git.jpg',
        likes: 45,
        retweets: 10,
        replies: 7,
    },
    {
        id: '3',
        userName: 'Grace Hopper',
        userHandle: 'ghopper',
        content: 'Un bug menos hoy. Gran día.',
        userAvatar: require('../assets/avatar/av3.jpg'),
        likes: 82,
        retweets: 15,
        replies: 4,
    },
    {
        id: '4',
        userName: 'Margaret Hamilton',
        userHandle: 'mhamilton',
        content: 'El software del Apolo 11 no se escribió solo 😉',
        // userAvatar: require('../assets/avatar/av4.jpg'),
        likes: 120,
        retweets: 28,
        replies: 9,
    },
    {
        id: '5',
        userName: 'Dennis Ritchie',
        userHandle: 'dmr',
        content: '“Hello, World!” nunca pasa de moda.',
        userAvatar: require('../assets/avatar/av5.jpg'),
        likes: 60,
        retweets: 18,
        replies: 3,
    },
    {
        id: '6',
        userName: 'Brendan Eich',
        userHandle: 'brendaneich',
        content: 'JavaScript en 10 días. Mala idea, buen resultado.',
        userAvatar: require('../assets/avatar/av6.jpg'),
        likes: 140,
        retweets: 22,
        replies: 11,
    },
    {
        id: '7',
        userName: 'Elon Musk',
        userHandle: 'elonm',
        content: 'Probando esta app creada en clase. Nice!',
        userAvatar: require('../assets/avatar/av7.jpg'),
        likes: 230,
        retweets: 33,
        replies: 19,
    },
    {
        id: '8',
        userName: 'Marie Curie',
        userHandle: 'marie_c',
        content: 'La ciencia avanza con pequeños pasos.',
        userAvatar: require('../assets/avatar/av8.jpg'),
        likes: 90,
        retweets: 21,
        replies: 8,
    },
    {
        id: '9',
        userName: 'Albert Einstein',
        userHandle: 'aeinstein',
        content: 'La imaginación es más importante que el conocimiento.',
        // userAvatar: require('../assets/avatar/av9.jpg'),
        likes: 200,
        retweets: 44,
        replies: 25,
    },
    {
        id: '10',
        userName: 'Katherine Johnson',
        userHandle: 'kjohnson',
        content: 'Las matemáticas nunca fallan ✨',
        userAvatar: require('../assets/avatar/av10.jpg'),
        likes: 76,
        retweets: 14,
        replies: 6,
    },
    {
        id: '11',
        userName: 'Satoshi Nakamoto',
        userHandle: 'nakamoto',
        content: 'La descentralización es el camino.',
        userAvatar: require('../assets/avatar/av1.jpg'),
        likes: 310,
        retweets: 55,
        replies: 17,
    },
    {
        id: '12',
        userName: 'Mark Zuckerberg',
        userHandle: 'zuck',
        content: '¿Qué podría salir mal? 🤖',
        userAvatar: require('../assets/avatar/av2.jpg'),
        likes: 150,
        retweets: 20,
        replies: 12,
    },
    {
        id: '13',
        userName: 'Bill Gates',
        userHandle: 'billg',
        content: 'Otro día, otra línea de código.',
        userAvatar: require('../assets/avatar/av3.jpg'),
        likes: 180,
        retweets: 27,
        replies: 14,
    },
    {
        id: '14',
        userName: 'Steve Jobs',
        userHandle: 'sjobs',
        content: 'La innovación distingue a los líderes.',
        // userAvatar: require('../assets/avatar/av4.jpg'),
        likes: 250,
        retweets: 49,
        replies: 33,
    },
    {
        id: '15',
        userName: 'Tim Berners-Lee',
        userHandle: 'tbl',
        content: 'La web debería ser para todos.',
        userAvatar: require('../assets/avatar/av5.jpg'),
        likes: 134,
        retweets: 23,
        replies: 9,
    },
    {
        id: '16',
        userName: 'Hedy Lamarr',
        userHandle: 'hedy_l',
        content: 'Inventar es algo maravilloso.',
        userAvatar: require('../assets/avatar/av6.jpg'),
        likes: 112,
        retweets: 19,
        replies: 7,
    },
    {
        id: '17',
        userName: 'Nikola Tesla',
        userHandle: 'ntesla',
        content: 'La electricidad siempre me ha fascinado ⚡',
        userAvatar: require('../assets/avatar/av7.jpg'),
        likes: 210,
        retweets: 37,
        replies: 15,
    },
    {
        id: '18',
        userName: 'Alan Turing',
        userHandle: 'aturing',
        content: 'A veces hay que romper códigos 🧠',
        userAvatar: require('../assets/avatar/av8.jpg'),
        likes: 300,
        retweets: 51,
        replies: 18,
    },
    {
        id: '19',
        userName: 'Joan Clarke',
        userHandle: 'jclarke',
        content: 'La lógica es una herramienta poderosa.',
        userAvatar: require('../assets/avatar/av9.jpg'),
        likes: 97,
        retweets: 16,
        replies: 5,
    },
    {
        id: '20',
        userName: 'John Carmack',
        userHandle: 'jcarmack',
        content: 'La optimización lo es todo.',
        userAvatar: require('../assets/avatar/av10.jpg'),
        likes: 122,
        retweets: 26,
        replies: 10,
    },
];
