/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/guardado` | `/guardado`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/hashtag` | `/hashtag`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/mensaje` | `/mensaje`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/usuario` | `/usuario`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/hashtag/[tag]` | `/hashtag/[tag]`, params: Router.UnknownInputParams & { tag: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/guardado` | `/guardado`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/hashtag` | `/hashtag`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/mensaje` | `/mensaje`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/usuario` | `/usuario`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/hashtag/[tag]` | `/hashtag/[tag]`, params: Router.UnknownOutputParams & { tag: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/feed${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/guardado${`?${string}` | `#${string}` | ''}` | `/guardado${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/hashtag${`?${string}` | `#${string}` | ''}` | `/hashtag${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/mensaje${`?${string}` | `#${string}` | ''}` | `/mensaje${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/usuario${`?${string}` | `#${string}` | ''}` | `/usuario${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/guardado` | `/guardado`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/hashtag` | `/hashtag`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/mensaje` | `/mensaje`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(drawer)'}${'/(tabs)'}/usuario` | `/usuario`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | `${'/(stack)'}/hashtag/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/hashtag/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(stack)'}/hashtag/[tag]` | `/hashtag/[tag]`, params: Router.UnknownInputParams & { tag: string | number; } };
    }
  }
}
